version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
      - checkout

      # Install Node.js and npm without sudo
      - run:
          name: Install Node.js and npm
          command: |
            apt-get update
            apt-get install -y nodejs npm

      # Install Netlify CLI
      - run:
          name: Install Netlify CLI
          command: |
            npm install -g netlify-cli

      # Install project dependencies and build
      - run:
          name: Install project dependencies and build
          command: |
            dotnet restore
            dotnet build --configuration Release

      # Deployment to Netlify
      - run:
          name: Deploy to Netlify
          command: |
            echo "Deploying to Netlify..."
            dotnet publish -c Release -o ./publish
            netlify deploy --prod --dir=./publish --auth $NETLIFY_AUTH_TOKEN
