version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
      - checkout

      # Build
      - run:
          name: Build project
          command: dotnet build --configuration Release
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs

      # Tests (if applicable)
      # - run:
      #     name: Run tests
      #     command: dotnet test

      # Deployment
      - deploy:
           name: Deploy to Netlify
           command: |
              echo "Deploying to Netlify..."
              dotnet publish -c Release -o ./publish
              npm install -g netlify-cli
              netlify deploy --prod --dir=./publish --auth $NETLIFY_AUTH_TOKEN

